- hosts: localhost
  vars:
    is_ubuntu: ansible_facts['distribution'] == "Ubuntu"
    is_archlinux: ansible_facts['distribution'] == "Archlinux"
  pre_tasks:
  - name: Update Apt
    when: ansible_facts['distribution'] == "Ubuntu"
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - name: Install zsh
      apt: name=zsh
