---
- name: Check if Cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes 
  tags: &rust_tags
    - rust

- name: Download Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags: *rust_tags

- name: Install Rust & Cargo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  tags: *rust_tags

# - name: Refresh shell
#   shell: source ~/.bashrc
#   tags: *rust_tags
      
# - name: Set Rust to the path
#   shell: |
#     echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> ~/.bashrc
#     source ~/.bashrc
#   args:
#     executable: /bin/bash

- name: Install rustfmt
  shell: |
    rustup component add rustfmt
  tags: *rust_tags

- name: Install clippy
  shell: |
    rustup component add clippy
  tags: *rust_tags

- name: Install rust-analyzer
  shell: |
    rustup component add rust-analyzer
  tags: *rust_tags

- name: Install cargo-edit
  shell: |
    cargo install cargo-edit
  tags: *rust_tags
    
- name: Install cargo-watch
  shell: |
    cargo install cargo-watch
  tags: *rust_tags

- name: Install Rust tools
  when: is_ubuntu
  shell: |
    cargo install starship
    cargo install fd
    cargo install exa
    cargo install bat
    cargo install ripgrep
    cargo install bottom
    cargo install dust
  tags: *rust_tags

